### PR TITLE
ROI Object selection GUI moved to App

### PR DESCRIPTION
**Pull request by VishalDhayalan**
Following from previous pull request, The feature has been moved to the App instead of the library.

### CODE REVIEW

**Comment by ukBaz** [comment]
A few PEP8 issues to address:
```
(venv) C:\CVzero>pycodestyle App
App\CVZero_monitor.py:1:11: E401 multiple imports on one line
App\CVZero_monitor.py:14:1: E302 expected 2 blank lines, found 1
App\CVZero_monitor.py:18:80: E501 line too long (134 > 79 characters)
App\CVZero_monitor.py:22:80: E501 line too long (96 > 79 characters)
App\CVZero_monitor.py:24:1: E305 expected 2 blank lines after class or function definition, found 1
App\CVZero_monitor.py:24:80: E501 line too long (82 > 79 characters)
App\CVZero_monitor.py:28:80: E501 line too long (104 > 79 characters)
App\CVZero_monitor.py:30:40: W291 trailing whitespace
App\CVZero_monitor.py:31:1: W293 blank line contains whitespace
App\CVZero_monitor.py:44:24: W292 no newline at end of file
```

**Comment by VishalDhayalan** [comment]
Sorry, VS code is not showing any formatting issues unless its something like indent levels not matching...

Does these PEP8 issues listed matter?

**Comment by ukBaz** [comment]
From: https://www.python.org/dev/peps/pep-0008/

> One of Guido's key insights is that code is read much more often than it is written. The guidelines provided here are intended to improve the readability of code and make it consistent across the wide spectrum of Python code. As PEP 20 says, "Readability counts".

> A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.

These issues will not stop the code from functioning but with a number of different contributors on this library is would be good to establish coding style guidelines that everyone follows.

**Comment by Corteil** [comment]
+1 code needs to be clear to read, ukBaz is correct, we need to keep to a style, the link ukBaz shared is the way to go.

**Comment by VishalDhayalan** [comment]
all PEP8 changes address except for the lines being apparently too long... It's confusing if half a line of code is in the next line, but feel free to change it.

**Pull request closed without merging**
