### PR TITLE
Streamlined cvzero library with ROI Object selection for learn function

### PR DESCRIPTION
**Pull request by VishalDhayalan**
- Removed new_image() method
- Added GUI based ROI object selection (using mouse) for learning
- Added guidance text on GUI outputs

Note: Had to manually update README.md to match the recent merge as this merge was made after I had pulled changes and developed the code.

### CODE REVIEW

**Comment by ukBaz** [comment]
My understanding of how this library is structured is that the GUI interaction functionality should be in the "App" module and not the "Library" part. @Corteil?

**Comment by VishalDhayalan** [comment]
@ukBaz the 'GUI' is just through imshow and allows the user to select objects on the image to learn, which is part of the library and the app is an addition to this right? 

We still need to be able to learn objects using the library...

**Comment by Corteil** [comment]
Yes GUI stuff should be in the app :-)

**Comment by VishalDhayalan** [comment]
How do I close a pull request?

**Comment by ukBaz** [comment]
https://help.github.com/en/articles/closing-a-pull-request

**Comment by VishalDhayalan** [comment]
Ohh I was trying to do it from an app but it wasn't getting closed. I'll do it from the website

**Pull request closed without merging**
